// Mocks generated by Mockito 5.4.6 from annotations
// in flauncher/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i14;
import 'dart:ui' as _i12;

import 'package:drift/drift.dart' as _i5;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i7;
import 'package:flauncher/database.dart' as _i6;
import 'package:flauncher/flauncher_channel.dart' as _i9;
import 'package:flauncher/gradients.dart' as _i2;
import 'package:flauncher/picsum_service.dart' as _i4;
import 'package:flauncher/providers/apps_service.dart' as _i13;
import 'package:flauncher/providers/button_mapping_service.dart' as _i15;
import 'package:flauncher/providers/settings_service.dart' as _i11;
import 'package:flauncher/providers/wallpaper_service.dart' as _i10;
import 'package:flauncher/unsplash_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFLauncherGradient_0 extends _i1.SmartFake
    implements _i2.FLauncherGradient {
  _FakeFLauncherGradient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePhoto_1 extends _i1.SmartFake implements _i3.Photo {
  _FakePhoto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePicsumPhoto_2 extends _i1.SmartFake implements _i4.PicsumPhoto {
  _FakePicsumPhoto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_3 extends _i1.SmartFake
    implements _i5.MigrationStrategy {
  _FakeMigrationStrategy_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$FLauncherDatabaseManager_4 extends _i1.SmartFake
    implements _i6.$FLauncherDatabaseManager {
  _Fake$FLauncherDatabaseManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppsTable_5 extends _i1.SmartFake implements _i6.$AppsTable {
  _Fake$AppsTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoriesTable_6 extends _i1.SmartFake
    implements _i6.$CategoriesTable {
  _Fake$CategoriesTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppsCategoriesTable_7 extends _i1.SmartFake
    implements _i6.$AppsCategoriesTable {
  _Fake$AppsCategoriesTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_8 extends _i1.SmartFake
    implements _i5.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_9 extends _i1.SmartFake
    implements _i5.GeneratedDatabase {
  _FakeGeneratedDatabase_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_10 extends _i1.SmartFake
    implements _i5.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_11 extends _i1.SmartFake
    implements _i5.DatabaseConnection {
  _FakeDatabaseConnection_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_12 extends _i1.SmartFake implements _i5.QueryExecutor {
  _FakeQueryExecutor_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_13 extends _i1.SmartFake
    implements _i7.StreamQueryStore {
  _FakeStreamQueryStore_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_14 extends _i1.SmartFake
    implements _i5.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_15 extends _i1.SmartFake implements _i5.Migrator {
  _FakeMigrator_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_16<T> extends _i1.SmartFake implements _i8.Future<T> {
  _FakeFuture_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_17<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.InsertStatement<T1, D1> {
  _FakeInsertStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_18<T extends _i5.Table, D> extends _i1.SmartFake
    implements _i5.UpdateStatement<T, D> {
  _FakeUpdateStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_19<T1 extends _i5.HasResultSet, D>
    extends _i1.SmartFake
    implements _i5.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_20<FirstT extends _i5.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i5.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_21<Row> extends _i1.SmartFake
    implements _i5.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_22<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_23<T> extends _i1.SmartFake implements _i5.Selectable<T> {
  _FakeSelectable_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_24 extends _i1.SmartFake
    implements _i5.GenerationContext {
  _FakeGenerationContext_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FLauncherChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherChannel extends _i1.Mock implements _i9.FLauncherChannel {
  MockFLauncherChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<dynamic>> getApplications() =>
      (super.noSuchMethod(
            Invocation.method(#getApplications, []),
            returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<bool> applicationExists(String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#applicationExists, [packageName]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> launchApp(String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#launchApp, [packageName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openAccessibilitySettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAccessibilitySettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openAppInfo(String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#openAppInfo, [packageName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> uninstallApp(String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#uninstallApp, [packageName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isDefaultLauncher() =>
      (super.noSuchMethod(
            Invocation.method(#isDefaultLauncher, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> checkForGetContentAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#checkForGetContentAvailability, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> startAmbientMode() =>
      (super.noSuchMethod(
            Invocation.method(#startAmbientMode, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addAppsChangedListener(void Function(Map<dynamic, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(#addAppsChangedListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<List<dynamic>> getButtonMappings() =>
      (super.noSuchMethod(
            Invocation.method(#getButtonMappings, []),
            returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<void> setButtonMapping(int? keyCode, String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#setButtonMapping, [keyCode, packageName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeButtonMapping(int? keyCode) =>
      (super.noSuchMethod(
            Invocation.method(#removeButtonMapping, [keyCode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<Map<dynamic, dynamic>> captureNextButton() =>
      (super.noSuchMethod(
            Invocation.method(#captureNextButton, []),
            returnValue: _i8.Stream<Map<dynamic, dynamic>>.empty(),
          )
          as _i8.Stream<Map<dynamic, dynamic>>);
}

/// A class which mocks [WallpaperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWallpaperService extends _i1.Mock implements _i10.WallpaperService {
  MockWallpaperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get wallpaperVersion =>
      (super.noSuchMethod(Invocation.getter(#wallpaperVersion), returnValue: 0)
          as int);

  @override
  bool get hasCurrentPicsumPhoto =>
      (super.noSuchMethod(
            Invocation.getter(#hasCurrentPicsumPhoto),
            returnValue: false,
          )
          as bool);

  @override
  bool get picsumGrayscale =>
      (super.noSuchMethod(
            Invocation.getter(#picsumGrayscale),
            returnValue: false,
          )
          as bool);

  @override
  bool get picsumBlurEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#picsumBlurEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i2.FLauncherGradient get gradient =>
      (super.noSuchMethod(
            Invocation.getter(#gradient),
            returnValue: _FakeFLauncherGradient_0(
              this,
              Invocation.getter(#gradient),
            ),
          )
          as _i2.FLauncherGradient);

  @override
  set settingsService(_i11.SettingsService? settingsService) =>
      super.noSuchMethod(
        Invocation.setter(#settingsService, settingsService),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> pickWallpaper() =>
      (super.noSuchMethod(
            Invocation.method(#pickWallpaper, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> randomFromUnsplash(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#randomFromUnsplash, [query]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.Photo>> searchFromUnsplash(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFromUnsplash, [query]),
            returnValue: _i8.Future<List<_i3.Photo>>.value(<_i3.Photo>[]),
          )
          as _i8.Future<List<_i3.Photo>>);

  @override
  _i8.Future<void> randomFromPicsum() =>
      (super.noSuchMethod(
            Invocation.method(#randomFromPicsum, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reapplyPicsumFilters({bool? grayscale = false, int? blur}) =>
      (super.noSuchMethod(
            Invocation.method(#reapplyPicsumFilters, [], {
              #grayscale: grayscale,
              #blur: blur,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setFromUnsplash(_i3.Photo? photo) =>
      (super.noSuchMethod(
            Invocation.method(#setFromUnsplash, [photo]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setGradient(_i2.FLauncherGradient? fLauncherGradient) =>
      (super.noSuchMethod(
            Invocation.method(#setGradient, [fLauncherGradient]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppsService extends _i1.Mock implements _i13.AppsService {
  MockAppsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  List<_i6.App> get applications =>
      (super.noSuchMethod(
            Invocation.getter(#applications),
            returnValue: <_i6.App>[],
          )
          as List<_i6.App>);

  @override
  List<_i6.CategoryWithApps> get categoriesWithApps =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesWithApps),
            returnValue: <_i6.CategoryWithApps>[],
          )
          as List<_i6.CategoryWithApps>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> launchApp(_i6.App? app) =>
      (super.noSuchMethod(
            Invocation.method(#launchApp, [app]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openAppInfo(_i6.App? app) =>
      (super.noSuchMethod(
            Invocation.method(#openAppInfo, [app]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> uninstallApp(_i6.App? app) =>
      (super.noSuchMethod(
            Invocation.method(#uninstallApp, [app]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> openAccessibilitySettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAccessibilitySettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isDefaultLauncher() =>
      (super.noSuchMethod(
            Invocation.method(#isDefaultLauncher, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> startAmbientMode() =>
      (super.noSuchMethod(
            Invocation.method(#startAmbientMode, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addToCategory(
    _i6.App? app,
    _i6.Category? category, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToCategory,
              [app, category],
              {#shouldNotifyListeners: shouldNotifyListeners},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromCategory(_i6.App? app, _i6.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCategory, [app, category]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveOrderInCategory(_i6.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrderInCategory, [category]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void reorderApplication(
    _i6.Category? category,
    int? oldIndex,
    int? newIndex,
  ) => super.noSuchMethod(
    Invocation.method(#reorderApplication, [category, oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> addCategory(
    String? categoryName, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addCategory,
              [categoryName],
              {#shouldNotifyListeners: shouldNotifyListeners},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> renameCategory(
    _i6.Category? category,
    String? categoryName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameCategory, [category, categoryName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCategory(_i6.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [category]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> moveCategory(int? oldIndex, int? newIndex) =>
      (super.noSuchMethod(
            Invocation.method(#moveCategory, [oldIndex, newIndex]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> hideApplication(_i6.App? application) =>
      (super.noSuchMethod(
            Invocation.method(#hideApplication, [application]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unHideApplication(_i6.App? application) =>
      (super.noSuchMethod(
            Invocation.method(#unHideApplication, [application]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCategoryType(
    _i6.Category? category,
    _i6.CategoryType? type, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCategoryType,
              [category, type],
              {#shouldNotifyListeners: shouldNotifyListeners},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCategorySort(
    _i6.Category? category,
    _i6.CategorySort? sort,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setCategorySort, [category, sort]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCategoryColumnsCount(
    _i6.Category? category,
    int? columnsCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setCategoryColumnsCount, [
              category,
              columnsCount,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCategoryRowHeight(
    _i6.Category? category,
    int? rowHeight,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setCategoryRowHeight, [category, rowHeight]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i11.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get use24HourTimeFormat =>
      (super.noSuchMethod(
            Invocation.getter(#use24HourTimeFormat),
            returnValue: false,
          )
          as bool);

  @override
  bool get appHighlightAnimationEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#appHighlightAnimationEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get unsplashEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#unsplashEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get picsumGrayscale =>
      (super.noSuchMethod(
            Invocation.getter(#picsumGrayscale),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> setUse24HourTimeFormat(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUse24HourTimeFormat, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setAppHighlightAnimationEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAppHighlightAnimationEnabled, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setGradientUuid(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGradientUuid, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setUnsplashAuthor(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUnsplashAuthor, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setPicsumPhotoId(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPicsumPhotoId, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setPicsumGrayscale(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPicsumGrayscale, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setPicsumBlur(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPicsumBlur, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UnsplashService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnsplashService extends _i1.Mock implements _i3.UnsplashService {
  MockUnsplashService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Photo> randomPhoto(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#randomPhoto, [query]),
            returnValue: _i8.Future<_i3.Photo>.value(
              _FakePhoto_1(this, Invocation.method(#randomPhoto, [query])),
            ),
          )
          as _i8.Future<_i3.Photo>);

  @override
  _i8.Future<List<_i3.Photo>> searchPhotos(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPhotos, [query]),
            returnValue: _i8.Future<List<_i3.Photo>>.value(<_i3.Photo>[]),
          )
          as _i8.Future<List<_i3.Photo>>);

  @override
  _i8.Future<_i14.Uint8List> downloadPhoto(_i3.Photo? photo) =>
      (super.noSuchMethod(
            Invocation.method(#downloadPhoto, [photo]),
            returnValue: _i8.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i8.Future<_i14.Uint8List>);
}

/// A class which mocks [PicsumService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPicsumService extends _i1.Mock implements _i4.PicsumService {
  MockPicsumService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.PicsumPhoto> randomPhoto() =>
      (super.noSuchMethod(
            Invocation.method(#randomPhoto, []),
            returnValue: _i8.Future<_i4.PicsumPhoto>.value(
              _FakePicsumPhoto_2(this, Invocation.method(#randomPhoto, [])),
            ),
          )
          as _i8.Future<_i4.PicsumPhoto>);

  @override
  _i8.Future<_i14.Uint8List> photoById(
    int? id, {
    bool? grayscale = false,
    int? blur,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #photoById,
              [id],
              {#grayscale: grayscale, #blur: blur},
            ),
            returnValue: _i8.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i8.Future<_i14.Uint8List>);
}

/// A class which mocks [ButtonMappingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockButtonMappingService extends _i1.Mock
    implements _i15.ButtonMappingService {
  MockButtonMappingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i15.ButtonMapping> get mappings =>
      (super.noSuchMethod(
            Invocation.getter(#mappings),
            returnValue: <_i15.ButtonMapping>[],
          )
          as List<_i15.ButtonMapping>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Stream<Map<dynamic, dynamic>> captureNextButton() =>
      (super.noSuchMethod(
            Invocation.method(#captureNextButton, []),
            returnValue: _i8.Stream<Map<dynamic, dynamic>>.empty(),
          )
          as _i8.Stream<Map<dynamic, dynamic>>);

  @override
  _i8.Future<void> setMapping(int? keyCode, String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#setMapping, [keyCode, packageName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeMapping(int? keyCode) =>
      (super.noSuchMethod(
            Invocation.method(#removeMapping, [keyCode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FLauncherDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherDatabase extends _i1.Mock implements _i6.FLauncherDatabase {
  MockFLauncherDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get wasCreated =>
      (super.noSuchMethod(Invocation.getter(#wasCreated), returnValue: false)
          as bool);

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i5.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_3(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i5.MigrationStrategy);

  @override
  set wasCreated(bool? value) => super.noSuchMethod(
    Invocation.setter(#wasCreated, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.$FLauncherDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$FLauncherDatabaseManager_4(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i6.$FLauncherDatabaseManager);

  @override
  _i6.$AppsTable get apps =>
      (super.noSuchMethod(
            Invocation.getter(#apps),
            returnValue: _Fake$AppsTable_5(this, Invocation.getter(#apps)),
          )
          as _i6.$AppsTable);

  @override
  _i6.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_6(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i6.$CategoriesTable);

  @override
  _i6.$AppsCategoriesTable get appsCategories =>
      (super.noSuchMethod(
            Invocation.getter(#appsCategories),
            returnValue: _Fake$AppsCategoriesTable_7(
              this,
              Invocation.getter(#appsCategories),
            ),
          )
          as _i6.$AppsCategoriesTable);

  @override
  Iterable<_i5.TableInfo<_i5.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i5.TableInfo<_i5.Table, Object?>>[],
          )
          as Iterable<_i5.TableInfo<_i5.Table, Object?>>);

  @override
  List<_i5.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i5.DatabaseSchemaEntity>[],
          )
          as List<_i5.DatabaseSchemaEntity>);

  @override
  _i5.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_8(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i5.StreamQueryUpdateRules);

  @override
  _i5.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_9(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i5.GeneratedDatabase);

  @override
  _i5.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_10(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i5.DriftDatabaseOptions);

  @override
  _i5.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_11(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i5.DatabaseConnection);

  @override
  _i5.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i16.dummyValue<_i5.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i5.SqlTypes);

  @override
  _i5.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_12(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i5.QueryExecutor);

  @override
  _i7.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_13(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i7.StreamQueryStore);

  @override
  _i5.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_14(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i5.DatabaseConnectionUser);

  @override
  _i8.Future<List<_i6.App>> listApplications() =>
      (super.noSuchMethod(
            Invocation.method(#listApplications, []),
            returnValue: _i8.Future<List<_i6.App>>.value(<_i6.App>[]),
          )
          as _i8.Future<List<_i6.App>>);

  @override
  _i8.Future<void> persistApps(List<_i6.AppsCompanion>? applications) =>
      (super.noSuchMethod(
            Invocation.method(#persistApps, [applications]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateApp(String? packageName, _i6.AppsCompanion? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateApp, [packageName, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteApps(List<String>? packageNames) =>
      (super.noSuchMethod(
            Invocation.method(#deleteApps, [packageNames]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> insertCategory(_i6.CategoriesCompanion? category) =>
      (super.noSuchMethod(
            Invocation.method(#insertCategory, [category]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateCategories(List<_i6.CategoriesCompanion>? values) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategories, [values]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateCategory(int? id, _i6.CategoriesCompanion? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [id, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAppCategory(int? categoryId, String? packageName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppCategory, [categoryId, packageName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> insertAppsCategories(
    List<_i6.AppsCategoriesCompanion>? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAppsCategories, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> replaceAppsCategories(
    List<_i6.AppsCategoriesCompanion>? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAppsCategories, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.CategoryWithApps>> listCategoriesWithVisibleApps() =>
      (super.noSuchMethod(
            Invocation.method(#listCategoriesWithVisibleApps, []),
            returnValue: _i8.Future<List<_i6.CategoryWithApps>>.value(
              <_i6.CategoryWithApps>[],
            ),
          )
          as _i8.Future<List<_i6.CategoryWithApps>>);

  @override
  _i8.Future<bool> isFreshInstall() =>
      (super.noSuchMethod(
            Invocation.method(#isFreshInstall, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<int?> nextAppCategoryOrder(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#nextAppCategoryOrder, [categoryId]),
            returnValue: _i8.Future<int?>.value(),
          )
          as _i8.Future<int?>);

  @override
  _i5.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_15(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i5.Migrator);

  @override
  _i8.Future<void> beforeOpen(
    _i5.QueryExecutor? executor,
    _i5.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Ret> computeWithDatabase<Ret, DB extends _i5.GeneratedDatabase>({
    required _i8.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i5.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i8.Future<Ret>.value(v),
                ) ??
                _FakeFuture_16<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i8.Future<Ret>);

  @override
  _i8.Stream<T> createStream<T extends Object>(
    _i7.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i8.Stream<T>.empty(),
          )
          as _i8.Stream<T>);

  @override
  T alias<T, D>(_i5.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i16.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i5.TableInfo<_i5.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i5.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Stream<Set<_i5.TableUpdate>> tableUpdates([
    _i5.TableUpdateQuery? query = const _i5.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i8.Stream<Set<_i5.TableUpdate>>.empty(),
          )
          as _i8.Stream<Set<_i5.TableUpdate>>);

  @override
  _i8.Future<T> doWhenOpened<T>(
    _i8.FutureOr<T> Function(_i5.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i8.Future<T>);

  @override
  _i5.InsertStatement<T, D> into<T extends _i5.Table, D>(
    _i5.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_17<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i5.InsertStatement<T, D>);

  @override
  _i5.UpdateStatement<Tbl, R> update<Tbl extends _i5.Table, R>(
    _i5.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_18<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i5.UpdateStatement<Tbl, R>);

  @override
  _i5.SimpleSelectStatement<T, R> select<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_19<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i5.SimpleSelectStatement<T, R>);

  @override
  _i5.JoinedSelectStatement<T, R> selectOnly<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_20<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i5.JoinedSelectStatement<T, R>);

  @override
  _i5.BaseSelectStatement<_i5.TypedResult> selectExpressions(
    Iterable<_i5.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_21<_i5.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i5.BaseSelectStatement<_i5.TypedResult>);

  @override
  _i5.DeleteStatement<T, D> delete<T extends _i5.Table, D>(
    _i5.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_22<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i5.DeleteStatement<T, D>);

  @override
  _i8.Future<int> customUpdate(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> customInsert(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i5.QueryRow>> customWriteReturning(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i8.Future<List<_i5.QueryRow>>.value(<_i5.QueryRow>[]),
          )
          as _i8.Future<List<_i5.QueryRow>>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelect(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_23<_i5.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i5.Selectable<_i5.QueryRow>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelectQuery(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_23<_i5.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i5.Selectable<_i5.QueryRow>);

  @override
  _i8.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T> transaction<T>(
    _i8.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<T> exclusively<T>(_i8.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i8.Future<T>);

  @override
  _i8.Future<void> batch(_i8.FutureOr<void> Function(_i5.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T> runWithInterceptor<T>(
    _i8.Future<T> Function()? action, {
    required _i5.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i8.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i8.Future<T>);

  @override
  _i5.GenerationContext $write(
    _i5.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_24(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  _i5.GenerationContext $writeInsertable(
    _i5.TableInfo<_i5.Table, dynamic>? table,
    _i5.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_24(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  _i5.GenerationContext $writeUpdateInsertable(
    _i5.TableInfo<_i5.Table, dynamic>? table,
    _i5.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeUpdateInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_24(
              this,
              Invocation.method(
                #$writeUpdateInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
